jobs:
- job: Redis5Linux
  displayName: 'Redis 5 on Linux'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build
    displayName: 'Build'

  - script: docker run -d --name test-redis --rm -p 6379:6379 redis:5
    displayName: 'Start Redis docker container'

  - script: dotnet run -- -c 10 -n 1000 -d 3B
    displayName: 'Execute benchmark'

  - script: docker container kill test-redis
    displayName: 'Cleanup Redis docker container'

- job: Redis4Linux
  displayName: 'Redis 4 on Linux'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build
    displayName: 'Build'

  - script: docker run -d --name test-redis --rm -p 6379:6379 redis:4
    displayName: 'Start Redis docker container'

  - script: dotnet run -- -c 10 -n 1000 -d 3B
    displayName: 'Execute benchmark'

  - script: docker container kill test-redis
    displayName: 'Cleanup Redis docker container'