jobs:
- job: Redis5Linuxv126
  displayName: 'Redis 5 (1.2.6) on Linux'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: docker run -d --name test-redis --rm -p 6379:6379 redis:5
    displayName: 'Start Redis docker container'

  - script: StackExchangeRedisVersion=1.2.6 dotnet run -- --clients 25 --num-requests 10000 --data-size 3B --quiet
    displayName: 'Execute benchmark'

  - script: docker container kill test-redis
    displayName: 'Cleanup Redis docker container'

- job: Redis4Linuxv126
  displayName: 'Redis 4 (1.2.6) on Linux'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: docker run -d --name test-redis --rm -p 6379:6379 redis:4
    displayName: 'Start Redis docker container'

  - script: StackExchangeRedisVersion=1.2.6 dotnet run -- --clients 25 --num-requests 10000 --data-size 3B --quiet
    displayName: 'Execute benchmark'

  - script: docker container kill test-redis
    displayName: 'Cleanup Redis docker container'

- job: Redis3Linuxv126
  displayName: 'Redis 3 (1.2.6) on Linux'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: docker run -d --name test-redis --rm -p 6379:6379 redis:3
    displayName: 'Start Redis docker container'

  - script: StackExchangeRedisVersion=1.2.6 dotnet run -- --clients 25 --num-requests 10000 --data-size 3B --quiet
    displayName: 'Execute benchmark'

  - script: docker container kill test-redis
    displayName: 'Cleanup Redis docker container'

- job: Redis5Linuxv20513
  displayName: 'Redis 5 (2.0.513) on Linux'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: docker run -d --name test-redis --rm -p 6379:6379 redis:5
    displayName: 'Start Redis docker container'

  - script: StackExchangeRedisVersion=2.0.513 dotnet run -- --clients 25 --num-requests 10000 --data-size 3B --quiet
    displayName: 'Execute benchmark'

  - script: docker container kill test-redis
    displayName: 'Cleanup Redis docker container'

- job: Redis4Linuxv20513
  displayName: 'Redis 4 (2.0.513) on Linux'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: docker run -d --name test-redis --rm -p 6379:6379 redis:4
    displayName: 'Start Redis docker container'

  - script: StackExchangeRedisVersion=2.0.513 dotnet run -- --clients 25 --num-requests 10000 --data-size 3B --quiet
    displayName: 'Execute benchmark'

  - script: docker container kill test-redis
    displayName: 'Cleanup Redis docker container'

- job: Redis3Linuxv20513
  displayName: 'Redis 3 (2.0.513) on Linux'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: docker run -d --name test-redis --rm -p 6379:6379 redis:3
    displayName: 'Start Redis docker container'

  - script: StackExchangeRedisVersion=2.0.513 dotnet run -- --clients 25 --num-requests 10000 --data-size 3B --quiet
    displayName: 'Execute benchmark'

  - script: docker container kill test-redis
    displayName: 'Cleanup Redis docker container'